Instala pacote guia-de-servicos-latest.rpm, não reinicia serviço em caso de erro - #69

diff --git a/scripts/alpha-deploy b/scripts/alpha-deploy
--- a/scripts/alpha-deploy
+++ b/scripts/alpha-deploy
@@ -1,9 +1,15 @@
 #!/bin/bash
 
 echo 'Instalando novo Guia de Serviços'
+sudo yum install -y guia-de-servicos-latest.rpm
 
-rpm -Uvh $(find guia-de-servicos*.rpm -type f)
+if [ "$?" -ne '0' ]; then
+  echo 'Erro na instalação. Abortando...'
+  exit -1
+fi
+
+echo 'Removendo pacote instalado'
+rm -rf guia-de-servicos-latest.rpm
 
 systemctl daemon-reload
 systemctl restart guia-de-servicos
-
